import "./globals.css";
import Header from "@/components/Header"
// import Contact from "@/app/Contact/page"


export const metadata = {
  title: 'create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html >
      <body>
        <Header />
        {children}
        {/* <Contact /> */}
      </body>
    </html>

  )
}